package appPack;

import DB.DB;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ferhat
 */
public class MusteriKayit extends javax.swing.JFrame {

    /**
     * Creates new form MüsteriKayit
     */
    public MusteriKayit() {
       initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/icons/Su_ikonu.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        m_txt_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        m_txt_surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        m_txt_number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        m_txt_address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMaximumSize(new java.awt.Dimension(470, 600));
        setMinimumSize(new java.awt.Dimension(470, 600));
        setPreferredSize(new java.awt.Dimension(470, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Adı");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 250, 53, 17);
        getContentPane().add(m_txt_name);
        m_txt_name.setBounds(180, 240, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Soyadı");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 290, 50, 17);
        getContentPane().add(m_txt_surname);
        m_txt_surname.setBounds(180, 280, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefon");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 330, 60, 17);
        getContentPane().add(m_txt_number);
        m_txt_number.setBounds(180, 320, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Adres");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 370, 50, 17);
        getContentPane().add(m_txt_address);
        m_txt_address.setBounds(180, 360, 180, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MusteriEkle.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 410, 70, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MainMenu.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(346, 13, 70, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MusteriKayitArkaPlan.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(470, 600));
        jLabel5.setMinimumSize(new java.awt.Dimension(470, 600));
        jLabel5.setPreferredSize(new java.awt.Dimension(470, 600));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, -140, 890, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name = m_txt_name.getText().trim().toUpperCase();
        String surname = m_txt_surname.getText().trim().toUpperCase();
        String number = m_txt_number.getText().trim();
        String address =m_txt_address.getText().trim();

        if( name.equals("") || surname.equals("") || number.equals("") || address.equals("")){ //boş olup olmadıkları kontrol edilir.
            JOptionPane.showMessageDialog(rootPane, "Lütfen tüm alanları doldurun");
            m_txt_name.requestFocus();

        }else{

            DB db = new DB();
            int status = db.customerSave(name, surname, number, address);
            db.close();

            if(status>0){
                MainFrame m = new MainFrame();
                m.setVisible(true);
                dispose();
            }

            if(status == -1){
                JOptionPane.showMessageDialog(rootPane, "Aynı telefon numarası ile kayıt var");
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainFrame register = new MainFrame();
        register.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField m_txt_address;
    private javax.swing.JTextField m_txt_name;
    private javax.swing.JTextField m_txt_number;
    private javax.swing.JTextField m_txt_surname;
    // End of variables declaration//GEN-END:variables
}
